version: '3.8'
services:
  teamhack_ca:
    image: innovanon/teamhack_ca
    container_name:  teamhack_ca
    ports:
      - "0.0.0.0:5002:5002/tcp"
    volumes:
      #- syslog-client:/etc/rsyslog.d:ro
      #- teamhack:/var/teamhack/etc:ro
      - ca-certs:/var/teamhack/certs:rw
      - ca-crl:/var/teamhack/crl:rw
      - ca-csr:/var/teamhac/csr:rw
      - ca-private:/var/teamhack/private:rw
    restart:         always
    #network_mode:    service:vpn-s1
    # TODO healthcheck by creating and revoking certs ?
    #healthcheck:
    #  test: ["CMD-SHELL", "python -c 'from requests import post; post(\"0.0.0.0\", data={\"host\":\"hackthebox.com\"})\"'"]
    #  interval:     10s
    #  timeout:       5s
    #  retries:       10
    #  test: ["CMD-SHELL", "exec 3<> /dev/tcp/0.0.0.0/3633 ; cat <&3 ; exec 3<&-"]
    depends_on:
      #postgres:
      #  condition: service_healthy
      syslog:
        condition: service_started
      #teamhack_dns:
      #  condition: service_healthy
    #networks:
    #  network:
    #    ipv4_address: 10.5.0.11
        
volumes:
  ca-certs:
    external: true
  ca-csr:
    external: true
  ca-crl:
    external: true
  ca-privaate:
    external: true
  #syslog-client:
  #  external: true

